### ISSUE TITLE
Add option for widget to communicate directly with Zarr store (no local HTTP server)

### ISSUE THREAD

**Issue by keller-mark** [vitessce/vitessce-python#322]
TODO: add `_store` parameters for all Zarr-based wrapper classes

- [x] `adata_store` parameter for AnnDataWrapper (#322)
- [ ] `img_store` parameter for `ImageOmeZarrWrapper`
- [ ] `img_store` parameter for `ObsSegmentationsOmeZarrWrapper`
- [ ] `zarr_store` parameter for `MultivecZarrWrapper` (depends on https://github.com/vitessce/vitessce/issues/1856)
- [ ] store parameter for SpatialDataWrapper (depends on #333 )

See https://github.com/manzt/anywidget/discussions/452 and https://github.com/manzt/anywidget/pull/453

**Comment by keller-mark** [comment]
Related to https://github.com/vitessce/vitessce/issues/1765

**Comment by keller-mark** [comment]
Fixed by https://github.com/vitessce/vitessce-python/issues/322
